### ISSUE TITLE
Request：Auto Parry or Auto Dodge

### ISSUE THREAD

**Issue by HandsomeWJ** [ok-oldking/ok-wuthering-waves#10]
Can you add feature to auto parry or auto dodge? When circle appear on enemy boss, especially for higher level enemies in Tower of Adversity

**Comment by ok-oldking** [comment]
The auto combat feature is already quite good. If you do something that most players can’t, you might get your account banned. Therefore, there is currently no plan to add an auto dodge feature. As for the auto parry function, since we’re constantly switching and attacking, most bosses can be auto parried.
